src/main/java/com/almeesoft/entities/Price.java
package com.almeesoft.entities;

import javax.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name = "PRICE")
@NamedQueries({
        @NamedQuery(name = "PRICE.getPriceById",query = "from Price where rentalUnit.id = :id"),
        @NamedQuery(name = "PRICE.updateData",query = "update Price set day = :day, week = :week, month = :month where rentalUnit.id = :id")
})
public class Price  extends BaseEntity{

    @Column(name = "day")
    private BigDecimal day;

    @Column(name = "week")
    private BigDecimal week;

    @Column(name = "month")
    private BigDecimal month;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_rental_unit")
    private RentalUnit rentalUnit;

    public boolean isPresent(){
        return !(day == null && week == null && month == null);
    }
    public RentalUnit getRentalUnit() {
        return rentalUnit;
    }

    public void setRentalUnit(RentalUnit rentalUnit) {
        this.rentalUnit = rentalUnit;
    }

    public BigDecimal getDay() {
        return day;
    }

    public void setDay(BigDecimal day) {
        this.day = day;
    }

    public BigDecimal getWeek() {
        return week;
    }

    public void setWeek(BigDecimal week) {
        this.week = week;
    }

    public BigDecimal getMonth() {
        return month;
    }

    public void setMonth(BigDecimal month) {
        this.month = month;
    }

    public Price() {
    }
}

src/main/java/com/almeesoft/entities/RentalUnit.java
package com.almeesoft.entities;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name = "RENTAL_UNIT")
@NamedQueries({
        @NamedQuery(name = "getRentalUnitById", query = "from RentalUnit r where r.id = :id "),
        @NamedQuery(name = "getMainRentalUnits", query = "from RentalUnit r where r.parentRentalUnit = null order by -id"),
        @NamedQuery(name = "getChildrenRentalUnitsById", query = "from RentalUnit r where r.parentRentalUnit.id = :id order by -id"),
        @NamedQuery(name = "getAllRentalUnit", query = "select r  from RentalUnit r order by -id"),
        @NamedQuery(name = "RENTAL_UNIT.getUsersRentalUnit", query = "from RentalUnit where user.id=:id order by -id "),
        @NamedQuery(name = "RENTAL_UNIT.getUsersRentalUnitForManage", query = "from RentalUnit where id != :current_id order by -id "),
        @NamedQuery(name = "RENTAL_UNIT.getUsersPolicy",query = "select r.policies from RentalUnit r where r.id = :id"),
        @NamedQuery(name = "RENTAL_UNIT.setPolicyValue",query = "update RentalUnit set policies = :policy where id = :id"),
        @NamedQuery(name = "RENTAL_UNIT.update",query = "update RentalUnit set name = :name, title = :title, description = :description where id = :id")


}
)

public class RentalUnit extends BaseEntity {


    @Column(name = "name")
    private String name;

    @Column(name = "title")
    private String title;

    @Column(name = "description")
    private String description;

    @Column(name = "plicies")
    private String policies;

    @Column(name = "full_address")
    private String fullAddress;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_user")
    private User user;

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "rentalUnit", cascade = CascadeType.ALL)
    private Price price;

    @OneToOne(mappedBy = "rentalUnit", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Address address;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rentalUnit", cascade = CascadeType.ALL)
    private List<RentalAmenity> rentalAmenities;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rentalUnit", cascade = CascadeType.ALL)
    private List<Image> images;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rentalUnit",cascade = CascadeType.ALL)
    private List<RentalPolicy> rentalPolicies;


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_parent", referencedColumnName = "id")
    private RentalUnit parentRentalUnit;


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "parentRentalUnit")
    private List<RentalUnit> sunRentalUnits;



    @Column(name = "showable")
    private Boolean showAble;


    public RentalUnit(String name, String title, String description, List<Image> images, List<RentalPolicy> polices, RentalUnit parentRentalUnit, List<RentalAmenity> amenities) {
        this.name = name;
        this.title = title;
        this.description = description;
        this.images = images;
        this.rentalPolicies = polices;
        this.parentRentalUnit = parentRentalUnit;
        this.rentalAmenities = amenities;

    }

    public RentalUnit() {
    }

    @Override
    public int hashCode() {
        return super.getId().hashCode();
    }

    @Override
    public String toString() {
        return super.getId() + " " + name + " " + title + " " + description;
    }

    @Override
    public boolean equals(Object obj) {
        return obj instanceof RentalUnit && this.getId().equals(((RentalUnit) obj).getId());
    }


    public List<RentalUnit> getSunRentalUnits() {
        return sunRentalUnits;
    }

    public void setSunRentalUnits(List<RentalUnit> sunRentalUnits) {
        this.sunRentalUnits = sunRentalUnits;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPolicies() {
        return policies;
    }

    public void setPolicies(String policies) {
        this.policies = policies;
    }

    public Price getPrice() {
        return price;
    }

    public void setPrice(Price price) {
        this.price = price;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public List<RentalAmenity> getRentalAmenities() {
        return rentalAmenities;
    }

    public void setRentalAmenities(List<RentalAmenity> rentalAmenities) {
        this.rentalAmenities = rentalAmenities;
    }

    public List<Image> getImages() {
        return images;
    }

    public void setImages(List<Image> images) {
        this.images = images;
    }

    public List<RentalPolicy> getRentalPolicies() {
        return rentalPolicies;
    }

    public void setRentalPolicies(List<RentalPolicy> rentalPolicies) {
        this.rentalPolicies = rentalPolicies;
    }

    public RentalUnit getParentRentalUnit() {
        return parentRentalUnit;
    }

    public void setParentRentalUnit(RentalUnit rentalUnit) {
        this.parentRentalUnit = rentalUnit;
    }

    public Boolean getShowAble() {
        return showAble;
    }

    public void setShowAble(Boolean showAble) {
        this.showAble = showAble;
    }


    public String getFullAddress() {
        return fullAddress;
    }

    public void setFullAddress(String fullAddress) {
        this.fullAddress = fullAddress;
    }
}

src/main/java/com/almeesoft/controller/anonimus_access/RentalUnitsController.java
package com.almeesoft.controller.anonimus_access;

import com.almeesoft.entities.RentalUnit;
import com.almeesoft.repository.AmenityRepository;
import com.almeesoft.repository.PoliceRepository;
import com.almeesoft.service.RentalUnitService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;
import java.util.logging.Logger;

@Controller
@RequestMapping(value = "/rentalunit")
public class RentalUnitsController {

    private Logger l = Logger.getLogger(this.getClass().getCanonicalName());

    @Autowired
    private RentalUnitService rentalUnitService;

    @RequestMapping
    public String getRentalUnitsById(Model model, @RequestParam(value = "id") int id) {

        List<RentalUnit> parentRentalUnitsById = rentalUnitService.getParentRentalUnitsById(id);
        RentalUnit byId = rentalUnitService.getById(id);
        System.out.println(rentalUnitService.getChildrenRentalUnitsById(id));
        System.out.println(rentalUnitService.getById(id).getParentRentalUnit());
        model.addAttribute("child", rentalUnitService.getChildrenRentalUnitsById(id));
        model.addAttribute("parent", rentalUnitService.getById(id).getParentRentalUnit());
        model.addAttribute("current", byId);
        model.addAttribute("addresses",rentalUnitService.getFullAddresses(byId));
        model.addAttribute("mainAddress",rentalUnitService.getMainAddress((long) id));
        model.addAttribute("amenities",rentalUnitService.getAmenitiesForView(byId));
        model.addAttribute("polices",rentalUnitService.getPoliciesForView(byId));

        return "rentalUnits";

    }
}

src/main/webapp/WEB-INF/pages/env.jsp
<%--
  Created by IntelliJ IDEA.
  User: Yuriy
  Date: 4/22/2016
  Time: 1:01 AM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>

<h3>${env.appName} - Appname</h3>
<h3>${env.mongoDBUrl} - mongoDBUrl</h3>
<h3>${env.mysqlHost} - mysqlHost</h3>
<h3>${env.mysqlPassword} - mysqlPAssword</h3>
<h3>${env.mysqlPort} - mysqlPort</h3>
<h3>${env.mysqlUsername} - mysqlUser</h3>
</body>
</html>

src/main/webapp/WEB-INF/pages/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<t:template>

    <div class="row  large-up-2">
        <c:forEach items="${mainRentalUnits}" var="rent">

            <div class="column">

                <c:if test="${rent.images.size() != 0}">
                    <a href="<c:url value="/rentalunit?id=${rent.id}"/>">
                        <img class="thumbnail"
                             src="<c:url  value="/uploaded_image?name=${rent.images.get(0).id}"/>" width="570"
                             height="470">
                    </a>
                </c:if>

                <c:if test="${rent.images.size() == 0}">
                    <img class="thumbnail"
                         src="<c:url  value="/resources/no-photo.png"/>" width="400" height="300">
                </c:if>

                <h5>${rent.name}</h5>


                <p><c:if test="${rent.price.day != null}">
                    $${rent.price.day}
                </c:if>

                </p>
                <a href="<c:url value="/rentalunit?id=${rent.id}"/>" class="button expanded">More</a>
            </div>

        </c:forEach>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

</t:template>

src/main/webapp/WEB-INF/pages/login.jsp
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<t:template>
    <c:url value="/j_spring_security_check" var="loginUrl"/>

    <div class="row">
        <form method="post" action="${loginUrl}">
            <sec:csrfInput/>
            <div class="row">
                <div class="large-3 large-offset-4">
                    <label>Login
                        <input type="text" name="login">
                    </label>
                </div>
                <div class="large-3 large-offset-4">
                    <label>Password
                        <input type="password" name="password">
                    </label>
                </div>
                <div class="large-offset-4">
                    <button type="submit" class="success button">Login</button>
                </div>
            </div>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
</t:template>

src/main/webapp/WEB-INF/pages/rentalUnits.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<t:template>

    <div class="row">
        <nav aria-label="You are here:" role="navigation">
            <ul class="breadcrumbs">
                <li><a href="<c:url value="/"/>">Landlord Home</a></li>
                <li><a href="#">Contact Landlord</a></li>
                <li><a href="#">Prepare CraigsList Ad</a></li>


            </ul>
        </nav>
        <div class="medium-6 columns">
                <%--<c:if test="${current.images.size() != 0}">--%>
                <%--<img class="thumbnail" src="<c:url value="/uploaded_image?name=${current.images.get(0).id}"/>">--%>
                <%--</c:if>--%>
                <%--<c:if test="${current.images.size() == 0}">--%>
                <%--<img class="thumbnail" src="<c:url value="/resources/no-photo.png"/>">--%>
                <%--</c:if>--%>
                <%--<div class="row small-up-4">--%>
                <%--<c:forEach items="${current.images}" begin="1" var="image">--%>
                <%--<div class="column">--%>
                <%--<img class="thumbnail" src="<c:url value="/uploaded_image?name=${image.id}"/>">--%>
                <%--</div>--%>
                <%--</c:forEach>--%>

                    <div class="fotorama" data-nav="thumbs">
                        <c:forEach items="${current.images}"  var="image">
                                <img  src="<c:url value="/uploaded_image?name=${image.id}"/>">
                        </c:forEach>
                    </div>
</div>
        <div class="medium-6 large-5 columns">
            <h3>${current.name}</h3>

            <c:if test="${current.parentRentalUnit != null}">
                <a href="<c:url value="/rentalunit?id=${current.parentRentalUnit.id}"/>">
                    <div class="media-object">
                        <div class="media-object-section">
                            <div class="thumbnail">

                                <c:if test="${current.parentRentalUnit.images.size() != 0}">
                                    <img src="<c:url value="/uploaded_image?name=${current.parentRentalUnit.images.get(0).id}"/>"
                                         width="100" height="100">
                                </c:if>
                                <c:if test="${current.images.size() == 0}">
                                    <img src="<c:url value="/resources/no-photo.png"/>" width="100" height="100">
                                </c:if>
                                Belongs to ${current.parentRentalUnit.name}
                            </div>

                        </div>

                    </div>
                </a>


            </c:if>
            <p> ${current.description}</p>

            <c:if test="${current.price.present}">


                <h5>Prices:</h5>
                <c:if test="${current.price.day != null}">
                    <p>For Day ${current.price.day}</p>
                </c:if>
                <c:if test="${current.price.week != null}">
                    <p>For Week ${current.price.week}</p>
                </c:if>
                <c:if test="${current.price.month != null}">
                    <p>For Month ${current.price.month}</p>
                </c:if>
            </c:if>
            <c:if test="${polices.size() != 0 || current.rentalPolicies.size() != 0}">
                <h5>Policies:</h5>
                <c:forEach items="${polices}" var="p">
                    <p class="ro_img">${p.name} <img src="<c:url value="/resources/question-speech-bubble.png"/>">
                    </p>
                    <div class="ro_hoverable">${p.description}</div>
                </c:forEach>
                <c:forEach items="${current.rentalPolicies}" var="p">
                    <p class="ro_img">${p.policy.name} <img
                            src="<c:url value="/resources/question-speech-bubble.png"/>">
                    </p>
                    <div class="ro_hoverable">${p.policy.description}</div>
                </c:forEach>
            </c:if>
            <c:if test="${current.policies != ''}">

                <h5>Additional Policy:</h5>
                <p>${current.policies}</p>
            </c:if>
            <c:if test="${amenities.size() != 0 || current.rentalAmenities.size() != 0}">
                <h5>Amenities</h5>
                <c:forEach items="${amenities}" var="amen">
                    <p>${amen.title}:
                        <c:if test="${amen.price!= null}">
                            ${amen.price}$
                        </c:if>
                        <c:if test="${amen.price == null}">
                            Free
                        </c:if>

                    </p>
                </c:forEach>
                <c:forEach items="${current.rentalAmenities}" var="amen">
                    <p>${amen.amenity.title}:
                        <c:if test="${amen.price!= null}">
                            ${amen.price}$
                        </c:if>
                        <c:if test="${amen.price == null}">
                            Free
                        </c:if>

                    </p>
                </c:forEach>
            </c:if>


            <sec:authorize access="hasRole('ADMIN')">
                <a href="<c:url value="/manage/rentalUnit/manageCurrentRentalUnit?id=${current.id}"/>"
                   class="button">Update</a>
            </sec:authorize>
            <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        </div>


        <div class="column row">

            <ul class="tabs" data-tabs id="example-tabs">
            </ul>
            <div class="tabs-content" data-tabs-content="example-tabs">
                <div class="tabs-panel is-active" id="panel12">
                    <div class="row medium-up-3 large-up-5">
                        <c:forEach items="${child}" var="c">
                            <div class="column">
                                <c:if test="${c.images.size() != 0}">
                                    <img class="thumbnail"
                                         src="<c:url value="/uploaded_image?name=${c.images.get(0).id}"/>">
                                </c:if>
                                <c:if test="${c.images.size() == 0}">
                                    <img class="thumbnail" src="<c:url value="/resources/no-photo.png"/>">
                                </c:if>
                                <h5>${c.name}
                                    <small>
                                        <c:if test="${c.price.day != null}">
                                            $${c.price.day}
                                        </c:if>
                                    </small>
                                </h5>
                                <p>${c.description}</p>
                                <a href="<c:url value="/rentalunit?id=${c.id}"/>"
                                   class="button hollow tiny expanded">See</a>
                            </div>
                        </c:forEach>
                    </div>
                </div>
            </div>
        </div>
                     <!-- 3 KB -->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script> <!-- 16 KB -->
</div>
</t:template>